{\rtf1\ansi\ansicpg950\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 ---\
- name: Enforce password policy on Ubuntu\
  hosts: all\
  become: true\
  gather_facts: true\
\
  vars:\
    # \uc0\u8592 \u8592  \u36889 \u35041 \u21487 \u20381 \u31293 \u26680 \u38656 \u27714 \u35519 \u25972 \
    policy:\
      pwquality:\
        minlen: 12\
        minclass: 3\
        maxrepeat: 3\
        usercheck: 1\
        retry: 3            # \uc0\u36664 \u20837 \u26032 \u23494 \u30908 \u22833 \u25943 \u21487 \u37325 \u35430 \u27425 \u25976 \u65288 PAM\u65289 \
      pass_max_days: 90     # \uc0\u23494 \u30908 \u21040 \u26399 \u65288 \u22825 \u65289 \
      pass_min_days: 1      # \uc0\u20841 \u27425 \u35722 \u26356 \u26368 \u23567 \u38291 \u38548 \u65288 \u22825 \u65289 \
      pass_warn_age: 7      # \uc0\u21040 \u26399 \u21069 \u35686 \u21578 \u65288 \u22825 \u65289 \
      remember: 5           # \uc0\u35352 \u20303 \u26368 \u36817  N \u32068 \u33290 \u23494 \u30908 \
      faillock:\
        deny: 5\
        unlock_time: 600\
        fail_interval: 900\
\
    # \uc0\u38656 \u35201 \u22871 \u29992 \u23494 \u30908 \u26399 \u38480 \u30340 \u26082 \u26377 \u24115 \u34399 \u65288 \u21487 \u25913 \u25104 \u20320 \u30340 \u28165 \u21934 \u65289 \
    users_to_update:\
      - user1\
\
  pre_tasks:\
    - name: Check OS family\
    - name: Fail if not Debian/Ubuntu\
      ansible.builtin.assert:\
        that:\
          - ansible_facts['os_family'] == "Debian"\
        fail_msg: "This playbook is intended for Ubuntu/Debian only."\
\
  tasks:\
    - name: Ensure required packages are installed\
      ansible.builtin.apt:\
        name:\
          - libpam-pwquality\
          - libpam-modules\
        state: present\
        update_cache: true\
\
    # ---- \uc0\u23494 \u30908 \u35079 \u38620 \u24230  pwquality.conf ----\
    - name: Configure /etc/security/pwquality.conf\
      ansible.builtin.blockinfile:\
        path: /etc/security/pwquality.conf\
        marker: "# \{mark\} ANSIBLE managed pwquality"\
        create: true\
        block: |\
          minlen = \{\{ policy.pwquality.minlen \}\}\
          minclass = \{\{ policy.pwquality.minclass \}\}\
          maxrepeat = \{\{ policy.pwquality.maxrepeat \}\}\
          usercheck = \{\{ policy.pwquality.usercheck \}\}\
\
    - name: Ensure pam_pwquality is referenced in /etc/pam.d/common-password\
      ansible.builtin.lineinfile:\
        path: /etc/pam.d/common-password\
        create: false\
        regexp: '^password\\s+requisite\\s+pam_pwquality\\.so'\
        line: "password requisite pam_pwquality.so retry=\{\{ policy.pwquality.retry \}\}"\
        insertbefore: '^password\\s+\\[success=1 default=ignore\\]\\s+pam_unix\\.so'\
        backup: true\
\
    # ---- \uc0\u31105 \u29992 \u37325 \u35079 \u33290 \u23494 \u30908  remember ----\
    - name: Ensure pam_unix has remember option (append or set)\
      ansible.builtin.replace:\
        path: /etc/pam.d/common-password\
        regexp: '^(password\\s+\\[.*\\]\\s+pam_unix\\.so.*?)(\\s+remember=\\d+)?\\s*$'\
        replace: '\\1 remember=\{\{ policy.remember \}\}'\
        backup: true\
\
    # ---- \uc0\u23494 \u30908 \u26399 \u38480  login.defs\u65288 \u38928 \u35373 \u20540 \u65289 ----\
    - name: Set PASS_MAX_DAYS\
      ansible.builtin.lineinfile:\
        path: /etc/login.defs\
        regexp: '^\\s*PASS_MAX_DAYS'\
        line: "PASS_MAX_DAYS   \{\{ policy.pass_max_days \}\}"\
        backup: true\
\
    - name: Set PASS_MIN_DAYS\
      ansible.builtin.lineinfile:\
        path: /etc/login.defs\
        regexp: '^\\s*PASS_MIN_DAYS'\
        line: "PASS_MIN_DAYS   \{\{ policy.pass_min_days \}\}"\
        backup: true\
\
    - name: Set PASS_WARN_AGE\
      ansible.builtin.lineinfile:\
        path: /etc/login.defs\
        regexp: '^\\s*PASS_WARN_AGE'\
        line: "PASS_WARN_AGE   \{\{ policy.pass_warn_age \}\}"\
        backup: true\
\
    # ---- \uc0\u30331 \u20837 \u22833 \u25943 \u37782 \u23450  pam_faillock ----\
    - name: Ensure faillock.conf parameters\
      ansible.builtin.blockinfile:\
        path: /etc/security/faillock.conf\
        marker: "# \{mark\} ANSIBLE managed faillock"\
        create: true\
        block: |\
          deny = \{\{ policy.faillock.deny \}\}\
          unlock_time = \{\{ policy.faillock.unlock_time \}\}\
          fail_interval = \{\{ policy.faillock.fail_interval \}\}\
\
    - name: Ensure pam_faillock lines in /etc/pam.d/common-auth (preauth)\
      ansible.builtin.blockinfile:\
        path: /etc/pam.d/common-auth\
        marker: "# \{mark\} ANSIBLE pam_faillock (preauth/authfail)"\
        insertafter: BOF\
        block: |\
          auth required pam_faillock.so preauth\
          auth required pam_faillock.so authfail\
\
    - name: Ensure pam_faillock line in /etc/pam.d/common-account\
      ansible.builtin.blockinfile:\
        path: /etc/pam.d/common-account\
        marker: "# \{mark\} ANSIBLE pam_faillock (account)"\
        insertafter: BOF\
        block: |\
          account required pam_faillock.so\
\
    # ---- \uc0\u23565 \u26082 \u26377 \u24115 \u34399 \u22871 \u29992 \u23494 \u30908 \u26399 \u38480 \u65288 \u27604  chage \u26356  idempotent\u65289 ----\
    - name: Enforce password aging on existing users\
      ansible.builtin.user:\
        name: "\{\{ item \}\}"\
        password_expire_max: "\{\{ policy.pass_max_days \}\}"\
        password_expire_min: "\{\{ policy.pass_min_days \}\}"\
        password_warn_days: "\{\{ policy.pass_warn_age \}\}"\
      loop: "\{\{ users_to_update \}\}"\
\
  handlers: []}