---
- name: Create test.txt file in /home/dgcadmin/test
  hosts: all
  become: true
  become_user: dgcadmin
  tasks:
    - name: Ensure /home/dgcadmin/test directory exists
      file:
        path: /home/dgcadmin/test
        state: directory
        owner: dgcadmin
        group: dgcadmin
        mode: '0755'

    - name: Ensure test.txt is created with content 'test'
      copy:
        dest: /home/dgcadmin/test/test.txt
        content: "test\n"
        owner: dgcadmin
        group: dgcadmin
        mode: '0644'
